### PR TITLE
Upgrade to lit 2

### LINKED ISSUE #32: Upgrade to Lit 2?
I see that the `@figspec/components` still uses lit-html 1.x and lit-element 2.x. I wonder if you'd want to upgrade to Lit 2 and the new `lit` library. The overall package has gotten smaller and faster and we have a React component generator in the `@lit-labs/react` package. See [lit.dev](https://lit.dev) for more info!

### PR DESCRIPTION
**Pull request by e111077**
Upgraded to Lit 2. Note that `@storybook/web-components@6.4.0` is where Lit 2 support was added.

Also it seems that the react workspace `build-storybook` command stopped working because it was missing `@babel/preset-typescript`

Fixes #32

### CODE REVIEW

**Comment by e111077** [comment]
Just ran prettier!

**Comment by e111077** [comment]
odd. Locally i've run

```bash
➜  figspec git:(lit-2) yarn prettier --check './**/src/**/*.{js,jsx,ts,tsx,css,html,md}'
yarn run v1.22.17
$ /Users/emarquez/Workspace/lit/figspec/node_modules/.bin/prettier --check './**/src/**/*.{js,jsx,ts,tsx,css,html,md}'
Checking formatting...
All matched files use Prettier code style!
✨  Done in 0.71s.
```

Any idea what is going wrong?

**Comment by pocka** [comment]
hmm... Probably my workflow file is doing something wrong. I'll merge anyway.
Thanks!

**Comment by e111077** [comment]
Cheers! Let me know if anything else is needed to prepare for any releases

**Pull request merged**
