### PR TITLE
Feat: add Figma metadata footer

### LINKED ISSUE #20: [feature request] Add timestamp and link to design
Similar to the iframe embed from addon-designs, it would be great to have a way to link to the figma design and open it either on web or the app, as well as a timestamp to know the last time the design was updated:

image

### PR DESCRIPTION
**Pull request by yannbf**
As part of #20, this PR introduces a footer component that displays some metadata about the design, exactly (and trying to mimic the looks) like the ones that are provided by embedded Figma:
image
Here it is ☝️ 

I also upgraded Storybook to from 6.0.26 to 6.2.9, there are some interesting stuff there, including an object editor in controls, so I thought it would be nice to do it :)

Few questions:
1 - Would we want to have the footer as optional? Should the docs be updated to mention that a link should always be included? We could make it so that if `link` is passed, the footer is shown. We could also provide a flag to show/hide, or whatever way you feel like brings the most value.

For addon-designs, the only change necessary to make this work properly should be to pass a new prop: `link` to the Figspec components.

Closes #20

### CODE REVIEW

**Comment by pocka** [comment]
@yannbf 
> 1 - Would we want to have the footer as optional? Should the docs be updated to mention that a link should always be included? We could make it so that if `link` is passed, the footer is shown. We could also provide a flag to show/hide, or whatever way you feel like brings the most value.

I prefer the optional one, both for customizability and backward compatibility.

The additional visibility flag would provide more extensible and programmatic API, but I think it's not needed considering the current status and our usage.

**Comment by yannbf** [comment]
> I prefer the optional one, both for customizability and backward compatibility.
> 
> The additional visibility flag would provide more extensible and programmatic API, but I think it's not needed considering the current status and our usage.

Sounds good! So how do you see this API? Let me know and I'll adjust it! If a link is passed, people can click on it and it will open Figma correctly. If a link is not passed, there's no way we can link to the project, but we can still display the name of the node and the timestamp.

**Review by pocka — COMMENTED** [review]
Could you add the definition for `link` attribute in [here](https://github.com/pocka/figspec/blob/master/packages/components/src/FigspecViewer/FigspecFileViewer.ts#L12-L49) and [here](https://github.com/pocka/figspec/blob/master/packages/components/src/FigspecViewer/FigspecFrameViewer.ts#L12-L49) too, so Storybook Controls Addon renders it in Controls panel?

**Comment by yannbf** [comment]
> Could you add the definition for `link` attribute in [here](https://github.com/pocka/figspec/blob/master/packages/components/src/FigspecViewer/FigspecFileViewer.ts#L12-L49) and [here](https://github.com/pocka/figspec/blob/master/packages/components/src/FigspecViewer/FigspecFrameViewer.ts#L12-L49) too, so Storybook Controls Addon renders it in Controls panel?

Definitely! I updated them and also added a check so that if `link` is not passed, the footer won't be rendered

**Comment by pocka** [comment]
Thanks!

**Pull request merged**
